version: '3.8'
services:
  blog-system-api:
    image: 211020/blog-system:1.0
    pull_policy: always
    container_name: blogsystem-api
    restart: unless-stopped
    environment:
      spring.data.redis.host: localhost
      spring.data.redis.password: 123456
      spring.datasource.url: jdbc:postgresql://localhost:5432/blogsystem
      spring.datasource.password: 123456
      spring.mail.password: fczw lwes bdph sctm
      spring.mail.username: blogsystem2110@gmail.com
      spring.mail.default-sender: blogsystem2110@gmail.com
      cloudinary.key: 117784362653246
      cloudinary.secret-key: XfcUsfz7LK7cdjj7Q5rf6BrxCEo
    ports:
      - "8080:8080"
