name: CI/CD Blog System Workflow
on:
  pull_request:
    branches: master_test_ci_cd
    paths:
      - 'src/**'
      - '.github/workflows/**'
  push:
    branches: master_test_ci_cd
    paths:
      - 'src/**'
      - '.github/workflows/**'
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  AWS_PRIVATE_KEY: ${{ secrets.BLOGSYSTEM_PRTIVATE_KEY }}
  AWS_IP: ${{ secrets.BLOGSYSTEM_PRTIVATE_KEY }}
  AWS_USERNAME: ${{ secrets.BLOGSYSTEM_USERNAME }}
  IMAGE_NAME: 'blogsystem'
jobs:
  deployment:
    name: Build docker image and deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Build Jar file
        run: mvn clean install -Dmaven.test.skip=true -P local

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t 211020/${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker image to Docker Hub
        run: docker push 211020/blogsystem:latest

      - name: Set permissions for private key
        run: |
          echo "${{ env.AWS_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
      - name: Deployment
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ env.AWS_USERNAME }}@${{ env.AWS_IP }} 'cd blogSystem'

      - name: Deployment completed Successfully
        run: echo "Deployment completed successfuly"
