name: CI/CD Blog System Workflow
on:
  pull_request:
    branches: master_test_ci_cd
    paths:
      - 'src/**'
      - '.github/workflows/**'
  push:
    branches: master_test_ci_cd
    paths:
      - 'src/**'
      - '.github/workflows/**'

jobs:
  deployment:
    name: Build docker image and deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Build Jar file
        run: mvn clean install -Dmaven.test.skip=true -P local

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t 211020/blogsystem:latest .

      - name: Push Docker image to Docker Hub
        run: docker push 211020/blogsystem:latest

      - name: Connect to AWS Lightsail, extract file and delete the file
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.BLOGSYSTEM_IP }}
          username: ${{ secrets.BLOGSYSTEM_USERNAME }}
          key: ${{ secrets.BLOGSYSTEM_PRTIVATE_KEY }}
          password: ""
          passphrase: ""
          port: 22
          script: |
            cd blogSystem 
            docker-compose up -d
      - name: Deployment completed Successfully
        run: echo "Deployment completed successfuly"
