name: CI/CD Blog System Workflow
on:
  pull_request:
    branches: master
    paths:
      - 'src/**'
      - '.github/workflows/**'
  push:
    branches: master_test_ci_cd
    paths:
      - 'src/**'
      - '.github/workflows/**'
jobs:
  setup-env:
    name: Setup Environment (jdk,maven, docker build)
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

  build:
    name: Build maven, docker image and push to docker hub
    runs-on: ubuntu-latest
    needs: setup-env
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Jar file
        run: mvn clean install -Dmaven.test.skip=true -P local

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/blogsystem:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/blogsystem:latest
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create PEM file
        run: |
          echo "${{ secrets.BLOGSYSTEM_PRTIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Start deployment with docker compose
        run: |
          ssh -v -o StrictHostKeyChecking=no -i key.pem ubuntu@54.255.101.71 
          cd blogSystem 
          docker-compose up -d
